title: "Interactive Art / Creative Code Fall 2018"
name: "Interactive Art / Creative Code"
description: The pretty course webpage for ARTTECH-3135 Interactive Art / Creative Code.
baseurl: s/ARTTECH3135-fall2018 # the subpath of your site, e.g. /blog
url: https://ajbajb.github.io # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima

#plugins:
    # - jekyll-redirect-from
    # - jekyll-sitemap
    # - jekyll-seo-tag
    #- jekyll-feed

# Collections
collections:
  assignments:
    output: true
    name: Assignments

# Default Values

defaults:
  - scope:
      path: ""
    values:
      author: ajbajb
  - scope:
      path: ""
      type: assignments
    values:
      layout: assignment
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
